### PR TITLE
provide r-ff 2.2-14

### PR DESCRIPTION
**Pull request by h-vetinari**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by h-vetinari** [comment]
@conda-forge-admin, please rerender

**Comment by h-vetinari** [comment]
@dpryan79 @bgruening @jdblischak 
This bump ran through without issues - could one of you take a look please?

I didn't know if I should move the build number from `1002` back to `1000` or `0`, took the former. Feel free to change if necessary, or give me a quick ping.

**Comment by dpryan79** [comment]
@h-vetinari Please use a build number of `0`.

**Comment by h-vetinari** [comment]
@dpryan79 
Done and green.

**Comment by dpryan79** [comment]
@conda-forge-admin, please rerender

**Comment by dpryan79** [comment]
Thanks @h-vetinari !

**Comment by h-vetinari** [comment]
Thanks as well! :)
How long does it take until the packages show up in conda-forge?

**Comment by dpryan79** [comment]
Give it 30-40 minutes (20 minutes to migrate across cache plus build time).

**Pull request merged**
